name: elk 

volumes:
  es_data:
    name: es_data

networks:
  web_net:
    name: web_net
    external: true
  app_net:
    name: app_net
    external: true

services:
  elasticsearch:
    build:
      context: elasticsearch/
      args:
        ELK_VERSION: ${ELK_VERSION}
    image: ${REGISTRY_URL}/${REGISTRY_DIR}/elasticsearch:${ELK_VERSION}
    volumes:
      - es_data:/usr/share/elasticsearch/data
    container_name: elasticsearch
    restart: on-failure
    environment:
      ES_JAVA_OPTS: "-Xmx1g -Xms1g"
      ELASTIC_PASSWORD: ${ELASTICSEARCH_PASSWORD}
      cluster.name: es-cluster
      bootstrap.memory_lock: "true"
      http.cors.enabled: "true"
    ulimits:
      memlock:
        soft: -1
        hard: -1
    networks:
      - web_net
      - app_net

  logstash:
    build:
      context: logstash/
      args:
        ELK_VERSION: ${ELK_VERSION}
    image: ${REGISTRY_URL}/${REGISTRY_DIR}/logstash:${ELK_VERSION}
    volumes:
      - ./logstash/pipeline:/usr/share/logstash/pipeline:ro
    ports:
      - "5000:5000"
      - "9600:9600"
    container_name: logstash
    restart: on-failure
    environment:
      LS_JAVA_OPTS: "-Xmx1g -Xms1g"
      ELASTICSEARCH_HOSTS: http://elasticsearch:9200
      ELASTICSEARCH_PASSWORD: ${ELASTICSEARCH_PASSWORD}
        
    networks:
      - app_net
    depends_on:
      - elasticsearch

  kibana:
    build:
      context: kibana/
      args:
        ELK_VERSION: ${ELK_VERSION}
    image: ${REGISTRY_URL}/${REGISTRY_DIR}/kibana:${ELK_VERSION}
    ports:
      - "5601:5601"
    container_name: kibana
    restart: on-failure
    environment:
      ELASTICSEARCH_PASSWORD: ${ELASTICSEARCH_PASSWORD}
    networks:
      - web_net
      - app_net
    depends_on:
      - elasticsearch
