name: gitlab-server 

networks:
  app_net:
    name: app_net
    external: true 
  web_net:
    name: web_net
    external: true 

volumes: 
  gitlab_log: 
    name: gitlab_log
  gitlab_data:
    name: gitlab_data
  gitlab_backup: 
    name: gitlab_backup
  gitlab_config:
    name: gitlab_config

services:
  gitlab:
    image: gitlab/gitlab-ce:${GITLAB_CE_VERSION}
    restart: ${RESTART_POLICY}
    container_name: gitlab
    hostname: "${GITLAB_EXTERNAL_DOMAIN}"
    environment:
      GITLAB_OMNIBUS_CONFIG: | 
        external_url "https://${GITLAB_EXTERNAL_DOMAIN}"
        nginx['enable'] = true
        nginx['client_max_body_size'] = '250m'
        nginx['redirect_http_to_https'] = false
        nginx['gzip_enabled'] = true
        nginx['listen_port'] = 80
        nginx['listen_https'] = false
        # ban login failed 
        gitlab_rails['rack_attack_git_basic_auth'] = {
        'enabled' => false,
        'ip_whitelist' => ["127.0.0.1"],
        'maxretry' => 10,
        'findtime' => 60,
        'bantime' => 3600
        }
        # registry congifuration 
        registry_external_url 'https://${REGISTRY_DOMAIN}'
        gitlab_rails['registry_enabled'] = true
        gitlab_rails['registry_host'] = "${REGISTRY_DOMAIN}"
        registry['enable'] = true
        registry['registry_http_addr'] = "localhost:5000"
        registry['log_directory'] = "/var/log/gitlab/registry"
        registry['env_directory'] = "/opt/gitlab/etc/registry/env"
        registry_nginx['enable'] = true
        registry_nginx['listen_port'] = 80

    ports:
#      - 22:22
      - 80:80
      - 443:443
    volumes:
      - 'gitlab_config:/etc/gitlab'
      - 'gitlab_log:/var/log/gitlab'
      - 'gitlab_data:/var/opt/gitlab'
      - 'gitlab_backup:/var/opt/gitlab/backups'
    networks:
      - app_net
      - web_net
    
