name: wordpress-with-nginx 

networks:
  app_net:
    name: app_net
    external: false 

volumes:
  wpdb_data:
    name: wpdb_data
  wp_data:
    name: wp_data

services:
  wpdb:
    image: mysql:5.7
    container_name: mysql
    volumes:
      - wpdb_data:/var/lib/mysql
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: sdfascsdvsfdvweliuoiquowecefcwaefef
      MYSQL_DATABASE: DockerMe
      MYSQL_USER: DockerMe
      MYSQL_PASSWORD: sdfascsdvsfdvweliuoiquowecefcwaefef
    networks:
      - app_net

  wordpress:
    image: wordpress:latest
    container_name: wordpress
    volumes:
      - wp_data:/var/www/html/
    depends_on:
      - wpdb
    restart: always
    environment:
      WORDPRESS_DB_HOST: wpdb:3306
      WORDPRESS_DB_USER: DockerMe
      WORDPRESS_DB_NAME: DockerMe
      WORDPRESS_DB_PASSWORD: sdfascsdvsfdvweliuoiquowecefcwaefef
    ports:
      - 8000:80
    networks:
      - app_net
