---
- name: pip install  
  ansible.builtin.pip:
    name: "{{ item }}"
    state: present
  loop:
    - PyYAML==6.0.1
    - docker-compose

- name: Creates directory
  ansible.builtin.file:
    path: "{{ service_path }}"
    state: directory

- name: copy compose file  
  ansible.builtin.copy:
    src: compose.yml
    dest: "{{ service_path }}/compose.yml"

- name: copy .env file and change variables
  ansible.builtin.template:
    src: .env.j2
    dest: "{{ service_path }}/.env"

- name: Pull all images on compose file 
  community.docker.docker_compose_v2_pull:
    project_src: "{{ service_path }}/compose.yml"

- name: Create And Start Service
  community.docker.docker_compose_v2_pull:
    project_src: "{{ service_path }}/compose.yml" 

