---
ssh_config:
  port: "{{ ansible_port }}"
  address: 0.0.0.0 
  LogLevel: VERBOS
  root_login: without-password
  MaxAuthTries: 3
  MaxSessions: 2
  AllowTcpForwarding: no  
  ClientAliveCountMax: 2
  UseDNS: no
  AllowUsers: {{ ansible_user }}
  AllowGroups: {{ ansible_user }}

